language: php

php:
  - '5.5.9'
  - '7.0'
  - '7.1'

services:
  - mysql

before_script:
    - travis_retry composer self-update
    - travis_retry composer require phpunit/phpunit:4.8.*
    - travis_retry composer install --no-interaction --prefer-source --dev
    - mysql -e 'CREATE DATABASE fias;'
    - mysql -uroot fias < tests/fias.sql


script:
    - vendor/bin/phpunit

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover tests/logs/coverage.clover