language: php

php:
  - '5.5.9'
  - '7.0'
  - '7.1'

services:
  - mysql

before_script:
    - travis_retry composer self-update
    - travis_retry composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master
    - travis_retry composer install --no-interaction --prefer-source --dev
    - mysql -e 'CREATE DATABASE fias;'
    - mysql -uroot fias < tests/fias.sql


script:
    - vendor/bin/phpunit

after_script:
    - php vendor/bin/coveralls -v
    - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "7.1" ]; then wget https://scrutinizer-ci.com/ocular.phar
    - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "7.1" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover